import {
  dance_website,
  bugtracker,
  chat_app,
  clone_tube,
  cloneflix,
  everything_dash,
  personal_site,
  gerald_hector_website,
  syntaxnsteps,
  workout_app,
} from "@/assets";

export const project_data = [
  {
    projectName: "SyntaxNSteps",
    url: "https://www.syntaxnsteps.com/",
    projectImg: syntaxnsteps,
    projectCaption: "SyntaxNSteps Company Site.",
    tags: ["React", "TypeScript", "Tailwind"],
  },
  {
    projectName: "Dance Website",
    url: "https://www.dimitrihectordance.com/",
    projectImg: dance_website,
    projectCaption: "Dance website.",
    tags: ["React", "TypeScript", "Tailwind", "Vite"],
  },
  {
    projectName: "Gerald Hector Site",
    url: "https://www.geraldhector.com/",
    projectImg: gerald_hector_website,
    projectCaption: "Client website.",
    tags: ["React", "TypeScript", "Tailwind", "Vite"],
  },
  {
    projectName: "Workout!",
    url: "https://workout-application-typescript.vercel.app/",
    projectImg: workout_app,
    projectCaption: "Workout application.",
    tags: ["React", "TypeScript"],
  },
  {
    projectName: "Bug Tracker",
    url: "https://bug-track-rouge.vercel.app/",
    projectImg: bugtracker,
    projectCaption: "Bug Tracker UI.",
    tags: ["React", "TypeScript", "Tailwind"],
  },
  {
    projectName: "CloneFlix",
    url: "https://cloneflix-pi.vercel.app/",
    projectImg: cloneflix,
    projectCaption: "UI only Netflix clone.",
    tags: ["Next.js", "TypeScript", "ShadCN", "Tailwind"],
  },
  {
    projectName: "Chat App",
    url: "https://chatapp-theta-rouge.vercel.app/",
    projectImg: chat_app,
    projectCaption: "Chat application UI.",
    tags: ["React", "TypeScript", "Zustand"],
  },
  {
    projectName: "CloneTube",
    url: "https://youtube-clone-phi-wine.vercel.app/",
    projectImg: clone_tube,
    projectCaption: "UI Only youtube clone.",
    tags: ["React", "TypeScript", "ShadCN", "Tailwind"],
  },
  {
    projectName: "Everything Dash",
    url: "https://llm-based-corporate-dash-aolp.vercel.app/",
    projectImg: everything_dash,
    projectCaption: "UI Only dashboard desktop site.",
    tags: ["React", "TypeScript", "ShadCN", "Tailwind"],
  },
  {
    projectName: "Personal Site (Old)",
    url: "https://prosite2024.vercel.app/",
    projectImg: personal_site,
    projectCaption: "Personal website.",
    tags: ["React", "TypeScript"],
  },
];
